"""add relationship between user and meal

Revision ID: 0ebedc2fca87
Revises: cf55dc09dd32
Create Date: 2025-10-01 20:28:43.019869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebedc2fca87'
down_revision = 'cf55dc09dd32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_meals_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meals_user_id', type_='foreignkey')

    # ### end Alembic commands ###