"""Add refresh token to User model

Revision ID: 67a2c6df07f8
Revises: 0ebedc2fca87
Create Date: 2025-10-02 10:56:00.229550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a2c6df07f8'
down_revision = '0ebedc2fca87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_expiration', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_users_refresh_token', ['refresh_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_refresh_token', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('refresh_token_expiration')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
