"""Add image_url to Meal model

Revision ID: 8c0d99dad6c6
Revises: 832834bc0609
Create Date: 2025-10-02 11:47:02.952917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0d99dad6c6'
down_revision = '832834bc0609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
